---

- name: Download Transmission
  sudo: yes
  apt:
    name: "transmission-daemon"
    state: present

- name: Restart Transmission
  sudo: yes
  service:
    name: "transmission-daemon"
    state: "stopped"

- name: Create the Transmission User
  sudo: yes
  user:
    name: "{{ transmission.user }}"
    password: "{{ transmission.password }}"
    state: present

- name: Create Dowloads folder
  sudo: yes
  file:
    path: "/home/{{ transmission.user }}/downloads"
    owner: "{{ transmission.user }}"
    state: directory
    mode: 0777

- name: Create incomplete folder
  sudo: yes
  file:
    path: "/home/{{ transmission.user }}/downloads/incomplete"
    owner: "{{ transmission.user }}"
    state: directory
    mode: 0777

- name: Copy config file
  sudo: yes
  template:
    src: "settings.j2"
    dest: "/etc/transmission-daemon/settings.json"

- name: Restart Transmission
  sudo: yes
  service:
    name: "transmission-daemon"
    state: "restarted"