---

- name: Download Transmission
  sudo: yes
  apt:
    name: "transmission-deamon"
    state: present

- name: Create the Transmission User
  sudo: yes
  user:
    name: "{{ transmission_user.name }}"
    password: "{{ transmission_user.password }}"
    state: present

- name: Create Dowloads folder
  sudo: yes
  file:
    path: "/home/{{ transmission_user.name }}/downloads"
    owner: "{{ transmission_user.name }}"
    state: directory
    mode: 0777

- name: Create incomplete folder
  sudo: yes
  file:
    path: "/home/{{ transmission_user.name }}/downloads/incomplete"
    owner: "{{ transmission_user.name }}"
    state: directory
    mode: 0777

- name: Copy config file
  sudo: yes
  template:
    src: "settings.j2"
    dest: "/etc/transmission-deamon/settings.json"

- name: Restart Transmission
  sudo: yes
  service:
    name: "transmission-deamon"
    state: "restarted"